# Generated by Django 4.2.5 on 2023-10-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='is_folder',
            field=models.BooleanField(),
        ),
    ]
